services:
  olist-agent-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: olist-agent-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
    restart: unless-stopped

  olist-streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: olist-streamlit
    command: streamlit run streamlitapp.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - olist-agent-api
    restart: unless-stopped